services:
  backend:
    volumes:
      - ./backend:/app
    environment:
      DEBUG: "true"

  frontend:
    volumes:
      - ./frontend:/FRONT
      - /FRONT/node_modules
    environment:
      NODE_ENV: development
